/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package th_buoi2;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author kevin101
 */
public class ThaoTacVoiFile extends javax.swing.JFrame {

    /**
     * Creates new form ThaoTacVoiFile
     */
    public ThaoTacVoiFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        txtNhapChuoi = new javax.swing.JTextField();
        txtNoidung = new javax.swing.JTextField();
        btnDocFileNhiPhan = new javax.swing.JButton();
        btnGhiFileNhiPhan = new javax.swing.JButton();
        btnDocFileVanBan = new javax.swing.JButton();
        btnGhiFileVanBan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập tên tập tin");

        jLabel2.setText("Nhập chuổi");

        jLabel3.setText("Nội dung file");

        txtFileName.setText("C:\\Users\\kevin101\\Desktop\\TH-Lap-trinh-mang");

        btnDocFileNhiPhan.setText("Đọc file nhị phân");
        btnDocFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileNhiPhanActionPerformed(evt);
            }
        });

        btnGhiFileNhiPhan.setText("Ghi file nhị phân");
        btnGhiFileNhiPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileNhiPhanActionPerformed(evt);
            }
        });

        btnDocFileVanBan.setText("Đọc file văn bản");
        btnDocFileVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileVanBanActionPerformed(evt);
            }
        });

        btnGhiFileVanBan.setText("Ghi file văn bản");
        btnGhiFileVanBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileVanBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(txtNhapChuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtNoidung))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDocFileNhiPhan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnGhiFileNhiPhan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDocFileVanBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGhiFileVanBan)))
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNhapChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNoidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocFileNhiPhan)
                    .addComponent(btnGhiFileNhiPhan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocFileVanBan)
                    .addComponent(btnGhiFileVanBan))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGhiFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileNhiPhanActionPerformed
        // TODO add your handling code here:
            byte a[] = new byte[20];
        File file;
        int i;
        char s[] = txtNhapChuoi.getText().toCharArray();
        for(i = 0; i < s.length; i++){
            a[i] = (byte)s[i];
        }
        try{
            file = new File(txtFileName.getText());
            FileOutputStream fo = new FileOutputStream(file);
            fo.write(a);
            fo.close();
        }catch(IOException e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnGhiFileNhiPhanActionPerformed

    private void btnDocFileNhiPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileNhiPhanActionPerformed
        // TODO add your handling code here:
       byte a[];
        File file;
        try{
            file = new File(txtFileName.getText());
            FileInputStream fi = new FileInputStream(file);
            a = new byte[fi.available()];
            fi.read(a);
            fi.close();
            txtNoidung.setText(new String(a));
        }catch(IOException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDocFileNhiPhanActionPerformed

    private void btnGhiFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileVanBanActionPerformed
        // TODO add your handling code here:
           try{
            FileWriter fw = new FileWriter(new File(txtFileName.getText()));
            fw.write(txtNhapChuoi.getText());
            fw.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGhiFileVanBanActionPerformed

    private void btnDocFileVanBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileVanBanActionPerformed
        // TODO add your handling code here:
        try{
            FileReader fr = new FileReader(new File(txtFileName.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5];
            while(fr.ready()){
                int len = fr.read(ca);
                sb.append(ca,0,len);
            }
            fr.close();
            txtNoidung.setText(sb+"");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDocFileVanBanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThaoTacVoiFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThaoTacVoiFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThaoTacVoiFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThaoTacVoiFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThaoTacVoiFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocFileNhiPhan;
    private javax.swing.JButton btnDocFileVanBan;
    private javax.swing.JButton btnGhiFileNhiPhan;
    private javax.swing.JButton btnGhiFileVanBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtNhapChuoi;
    private javax.swing.JTextField txtNoidung;
    // End of variables declaration//GEN-END:variables
}
